---
language: python
sudo: false
python:
  - 3.5
  - 3.6
install:
  - pip install -r requirements.txt
script:
  - flake8 data_manager_select_index_by_path/data_manager
  - yamllint $(git ls-files *.yml)
  - >
    planemo lint
    data_manager_select_index_by_path/data_manager/data_manager_select_index_by_path.xml
  - >
    pytest
    --cov-report xml
    --cov data_manager_select_index_by_path/data_manager
    data_manager_select_index_by_path/data_manager/test_path_name_value_key_manager.py
  - python-codacy-coverage -r coverage.xml
