---
categories: [Data Managers]
description:
  A data manager to register already build indexes in Galaxy's data tables
remote_repository_url:
  https://github.com/LUMC/lumc-galaxy-tools/tree/master/data_manager_select_index_by_path
homepage_url:
  https://github.com/LUMC/lumc-galaxy-tools
long_description: |
  This tool can link galaxy to already built indexes on the filesystem.
  This tool currently supports the following formats:
    - FASTA (for all_fasta table)
    - Bowtie index
    - Bowtie2 index
    - BWA index
    - Fasta index (.fai)
    - Hisat2 index
    - Kallisto index
    - Picard index
    - GATK sorted picard index
    - bwameth index
    - GTF file
    - Star index
    - Tophat2 index

name: data_manager_select_index_by_path
owner: rhpvorderman
type: unrestricted
exclude:
  - test-data/
  - data_manager/test_path_name_value_key_manager.py
  - README.md
